/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateContestInput = {
  id?: string | null,
  contestID: string,
  sort: number,
  contestContentAnn: string,
  title: string,
  ps1?: string | null,
  ps2?: string | null,
  ps3?: string | null,
  ps4?: string | null,
  ps5?: string | null,
  q1?: string | null,
  q2?: string | null,
  q3?: string | null,
  q4?: string | null,
  q5?: string | null,
  q6?: string | null,
  q7?: string | null,
  q8?: string | null,
  q9?: string | null,
  q10?: string | null,
  a1?: string | null,
  a2?: string | null,
  a3?: string | null,
  a4?: string | null,
  a5?: string | null,
  a6?: string | null,
  a7?: string | null,
  a8?: string | null,
  a9?: string | null,
  a10?: string | null,
  scheduledTime: number,
};

export type ModelContestConditionInput = {
  contestID?: ModelIDInput | null,
  sort?: ModelIntInput | null,
  contestContentAnn?: ModelStringInput | null,
  title?: ModelStringInput | null,
  ps1?: ModelStringInput | null,
  ps2?: ModelStringInput | null,
  ps3?: ModelStringInput | null,
  ps4?: ModelStringInput | null,
  ps5?: ModelStringInput | null,
  q1?: ModelStringInput | null,
  q2?: ModelStringInput | null,
  q3?: ModelStringInput | null,
  q4?: ModelStringInput | null,
  q5?: ModelStringInput | null,
  q6?: ModelStringInput | null,
  q7?: ModelStringInput | null,
  q8?: ModelStringInput | null,
  q9?: ModelStringInput | null,
  q10?: ModelStringInput | null,
  a1?: ModelStringInput | null,
  a2?: ModelStringInput | null,
  a3?: ModelStringInput | null,
  a4?: ModelStringInput | null,
  a5?: ModelStringInput | null,
  a6?: ModelStringInput | null,
  a7?: ModelStringInput | null,
  a8?: ModelStringInput | null,
  a9?: ModelStringInput | null,
  a10?: ModelStringInput | null,
  scheduledTime?: ModelFloatInput | null,
  and?: Array< ModelContestConditionInput | null > | null,
  or?: Array< ModelContestConditionInput | null > | null,
  not?: ModelContestConditionInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelFloatInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type Contest = {
  __typename: "Contest",
  id: string,
  contestID: string,
  sort: number,
  contestContentAnn: string,
  title: string,
  ps1?: string | null,
  ps2?: string | null,
  ps3?: string | null,
  ps4?: string | null,
  ps5?: string | null,
  q1?: string | null,
  q2?: string | null,
  q3?: string | null,
  q4?: string | null,
  q5?: string | null,
  q6?: string | null,
  q7?: string | null,
  q8?: string | null,
  q9?: string | null,
  q10?: string | null,
  a1?: string | null,
  a2?: string | null,
  a3?: string | null,
  a4?: string | null,
  a5?: string | null,
  a6?: string | null,
  a7?: string | null,
  a8?: string | null,
  a9?: string | null,
  a10?: string | null,
  scheduledTime: number,
  createdAt: string,
  updatedAt: string,
  owner?: string | null,
  answerAttempts?: ModelContestAnswerConnection | null,
};

export type ModelContestAnswerConnection = {
  __typename: "ModelContestAnswerConnection",
  items?:  Array<ContestAnswer | null > | null,
  nextToken?: string | null,
};

export type ContestAnswer = {
  __typename: "ContestAnswer",
  id: string,
  contestAnswerID: string,
  score: number,
  ca1?: number | null,
  ca2?: number | null,
  ca3?: number | null,
  ca4?: number | null,
  ca5?: number | null,
  ca6?: number | null,
  ca7?: number | null,
  ca8?: number | null,
  ca9?: number | null,
  ca10?: number | null,
  contestID: string,
  createdAt: string,
  updatedAt: string,
  contest?: Contest | null,
  owner?: string | null,
};

export type UpdateContestInput = {
  id: string,
  contestID?: string | null,
  sort?: number | null,
  contestContentAnn?: string | null,
  title?: string | null,
  ps1?: string | null,
  ps2?: string | null,
  ps3?: string | null,
  ps4?: string | null,
  ps5?: string | null,
  q1?: string | null,
  q2?: string | null,
  q3?: string | null,
  q4?: string | null,
  q5?: string | null,
  q6?: string | null,
  q7?: string | null,
  q8?: string | null,
  q9?: string | null,
  q10?: string | null,
  a1?: string | null,
  a2?: string | null,
  a3?: string | null,
  a4?: string | null,
  a5?: string | null,
  a6?: string | null,
  a7?: string | null,
  a8?: string | null,
  a9?: string | null,
  a10?: string | null,
  scheduledTime?: number | null,
};

export type DeleteContestInput = {
  id: string,
};

export type CreateContestAnswerInput = {
  id?: string | null,
  contestAnswerID: string,
  score: number,
  ca1?: number | null,
  ca2?: number | null,
  ca3?: number | null,
  ca4?: number | null,
  ca5?: number | null,
  ca6?: number | null,
  ca7?: number | null,
  ca8?: number | null,
  ca9?: number | null,
  ca10?: number | null,
  contestID: string,
};

export type ModelContestAnswerConditionInput = {
  contestAnswerID?: ModelIDInput | null,
  score?: ModelIntInput | null,
  ca1?: ModelIntInput | null,
  ca2?: ModelIntInput | null,
  ca3?: ModelIntInput | null,
  ca4?: ModelIntInput | null,
  ca5?: ModelIntInput | null,
  ca6?: ModelIntInput | null,
  ca7?: ModelIntInput | null,
  ca8?: ModelIntInput | null,
  ca9?: ModelIntInput | null,
  ca10?: ModelIntInput | null,
  contestID?: ModelIDInput | null,
  and?: Array< ModelContestAnswerConditionInput | null > | null,
  or?: Array< ModelContestAnswerConditionInput | null > | null,
  not?: ModelContestAnswerConditionInput | null,
};

export type UpdateContestAnswerInput = {
  id: string,
  contestAnswerID?: string | null,
  score?: number | null,
  ca1?: number | null,
  ca2?: number | null,
  ca3?: number | null,
  ca4?: number | null,
  ca5?: number | null,
  ca6?: number | null,
  ca7?: number | null,
  ca8?: number | null,
  ca9?: number | null,
  ca10?: number | null,
  contestID?: string | null,
};

export type DeleteContestAnswerInput = {
  id: string,
};

export type ModelContestFilterInput = {
  id?: ModelIDInput | null,
  contestID?: ModelIDInput | null,
  sort?: ModelIntInput | null,
  contestContentAnn?: ModelStringInput | null,
  title?: ModelStringInput | null,
  ps1?: ModelStringInput | null,
  ps2?: ModelStringInput | null,
  ps3?: ModelStringInput | null,
  ps4?: ModelStringInput | null,
  ps5?: ModelStringInput | null,
  q1?: ModelStringInput | null,
  q2?: ModelStringInput | null,
  q3?: ModelStringInput | null,
  q4?: ModelStringInput | null,
  q5?: ModelStringInput | null,
  q6?: ModelStringInput | null,
  q7?: ModelStringInput | null,
  q8?: ModelStringInput | null,
  q9?: ModelStringInput | null,
  q10?: ModelStringInput | null,
  a1?: ModelStringInput | null,
  a2?: ModelStringInput | null,
  a3?: ModelStringInput | null,
  a4?: ModelStringInput | null,
  a5?: ModelStringInput | null,
  a6?: ModelStringInput | null,
  a7?: ModelStringInput | null,
  a8?: ModelStringInput | null,
  a9?: ModelStringInput | null,
  a10?: ModelStringInput | null,
  scheduledTime?: ModelFloatInput | null,
  and?: Array< ModelContestFilterInput | null > | null,
  or?: Array< ModelContestFilterInput | null > | null,
  not?: ModelContestFilterInput | null,
};

export type ModelContestConnection = {
  __typename: "ModelContestConnection",
  items?:  Array<Contest | null > | null,
  nextToken?: string | null,
};

export type ModelContestAnswerFilterInput = {
  id?: ModelIDInput | null,
  contestAnswerID?: ModelIDInput | null,
  score?: ModelIntInput | null,
  ca1?: ModelIntInput | null,
  ca2?: ModelIntInput | null,
  ca3?: ModelIntInput | null,
  ca4?: ModelIntInput | null,
  ca5?: ModelIntInput | null,
  ca6?: ModelIntInput | null,
  ca7?: ModelIntInput | null,
  ca8?: ModelIntInput | null,
  ca9?: ModelIntInput | null,
  ca10?: ModelIntInput | null,
  contestID?: ModelIDInput | null,
  and?: Array< ModelContestAnswerFilterInput | null > | null,
  or?: Array< ModelContestAnswerFilterInput | null > | null,
  not?: ModelContestAnswerFilterInput | null,
};

export type CreateContestMutationVariables = {
  input: CreateContestInput,
  condition?: ModelContestConditionInput | null,
};

export type CreateContestMutation = {
  createContest?:  {
    __typename: "Contest",
    id: string,
    contestID: string,
    sort: number,
    contestContentAnn: string,
    title: string,
    ps1?: string | null,
    ps2?: string | null,
    ps3?: string | null,
    ps4?: string | null,
    ps5?: string | null,
    q1?: string | null,
    q2?: string | null,
    q3?: string | null,
    q4?: string | null,
    q5?: string | null,
    q6?: string | null,
    q7?: string | null,
    q8?: string | null,
    q9?: string | null,
    q10?: string | null,
    a1?: string | null,
    a2?: string | null,
    a3?: string | null,
    a4?: string | null,
    a5?: string | null,
    a6?: string | null,
    a7?: string | null,
    a8?: string | null,
    a9?: string | null,
    a10?: string | null,
    scheduledTime: number,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
    answerAttempts?:  {
      __typename: "ModelContestAnswerConnection",
      items?:  Array< {
        __typename: "ContestAnswer",
        id: string,
        contestAnswerID: string,
        score: number,
        ca1?: number | null,
        ca2?: number | null,
        ca3?: number | null,
        ca4?: number | null,
        ca5?: number | null,
        ca6?: number | null,
        ca7?: number | null,
        ca8?: number | null,
        ca9?: number | null,
        ca10?: number | null,
        contestID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null > | null,
      nextToken?: string | null,
    } | null,
  } | null,
};

export type UpdateContestMutationVariables = {
  input: UpdateContestInput,
  condition?: ModelContestConditionInput | null,
};

export type UpdateContestMutation = {
  updateContest?:  {
    __typename: "Contest",
    id: string,
    contestID: string,
    sort: number,
    contestContentAnn: string,
    title: string,
    ps1?: string | null,
    ps2?: string | null,
    ps3?: string | null,
    ps4?: string | null,
    ps5?: string | null,
    q1?: string | null,
    q2?: string | null,
    q3?: string | null,
    q4?: string | null,
    q5?: string | null,
    q6?: string | null,
    q7?: string | null,
    q8?: string | null,
    q9?: string | null,
    q10?: string | null,
    a1?: string | null,
    a2?: string | null,
    a3?: string | null,
    a4?: string | null,
    a5?: string | null,
    a6?: string | null,
    a7?: string | null,
    a8?: string | null,
    a9?: string | null,
    a10?: string | null,
    scheduledTime: number,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
    answerAttempts?:  {
      __typename: "ModelContestAnswerConnection",
      items?:  Array< {
        __typename: "ContestAnswer",
        id: string,
        contestAnswerID: string,
        score: number,
        ca1?: number | null,
        ca2?: number | null,
        ca3?: number | null,
        ca4?: number | null,
        ca5?: number | null,
        ca6?: number | null,
        ca7?: number | null,
        ca8?: number | null,
        ca9?: number | null,
        ca10?: number | null,
        contestID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null > | null,
      nextToken?: string | null,
    } | null,
  } | null,
};

export type DeleteContestMutationVariables = {
  input: DeleteContestInput,
  condition?: ModelContestConditionInput | null,
};

export type DeleteContestMutation = {
  deleteContest?:  {
    __typename: "Contest",
    id: string,
    contestID: string,
    sort: number,
    contestContentAnn: string,
    title: string,
    ps1?: string | null,
    ps2?: string | null,
    ps3?: string | null,
    ps4?: string | null,
    ps5?: string | null,
    q1?: string | null,
    q2?: string | null,
    q3?: string | null,
    q4?: string | null,
    q5?: string | null,
    q6?: string | null,
    q7?: string | null,
    q8?: string | null,
    q9?: string | null,
    q10?: string | null,
    a1?: string | null,
    a2?: string | null,
    a3?: string | null,
    a4?: string | null,
    a5?: string | null,
    a6?: string | null,
    a7?: string | null,
    a8?: string | null,
    a9?: string | null,
    a10?: string | null,
    scheduledTime: number,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
    answerAttempts?:  {
      __typename: "ModelContestAnswerConnection",
      items?:  Array< {
        __typename: "ContestAnswer",
        id: string,
        contestAnswerID: string,
        score: number,
        ca1?: number | null,
        ca2?: number | null,
        ca3?: number | null,
        ca4?: number | null,
        ca5?: number | null,
        ca6?: number | null,
        ca7?: number | null,
        ca8?: number | null,
        ca9?: number | null,
        ca10?: number | null,
        contestID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null > | null,
      nextToken?: string | null,
    } | null,
  } | null,
};

export type CreateContestAnswerMutationVariables = {
  input: CreateContestAnswerInput,
  condition?: ModelContestAnswerConditionInput | null,
};

export type CreateContestAnswerMutation = {
  createContestAnswer?:  {
    __typename: "ContestAnswer",
    id: string,
    contestAnswerID: string,
    score: number,
    ca1?: number | null,
    ca2?: number | null,
    ca3?: number | null,
    ca4?: number | null,
    ca5?: number | null,
    ca6?: number | null,
    ca7?: number | null,
    ca8?: number | null,
    ca9?: number | null,
    ca10?: number | null,
    contestID: string,
    createdAt: string,
    updatedAt: string,
    contest?:  {
      __typename: "Contest",
      id: string,
      contestID: string,
      sort: number,
      contestContentAnn: string,
      title: string,
      ps1?: string | null,
      ps2?: string | null,
      ps3?: string | null,
      ps4?: string | null,
      ps5?: string | null,
      q1?: string | null,
      q2?: string | null,
      q3?: string | null,
      q4?: string | null,
      q5?: string | null,
      q6?: string | null,
      q7?: string | null,
      q8?: string | null,
      q9?: string | null,
      q10?: string | null,
      a1?: string | null,
      a2?: string | null,
      a3?: string | null,
      a4?: string | null,
      a5?: string | null,
      a6?: string | null,
      a7?: string | null,
      a8?: string | null,
      a9?: string | null,
      a10?: string | null,
      scheduledTime: number,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
      answerAttempts?:  {
        __typename: "ModelContestAnswerConnection",
        nextToken?: string | null,
      } | null,
    } | null,
    owner?: string | null,
  } | null,
};

export type UpdateContestAnswerMutationVariables = {
  input: UpdateContestAnswerInput,
  condition?: ModelContestAnswerConditionInput | null,
};

export type UpdateContestAnswerMutation = {
  updateContestAnswer?:  {
    __typename: "ContestAnswer",
    id: string,
    contestAnswerID: string,
    score: number,
    ca1?: number | null,
    ca2?: number | null,
    ca3?: number | null,
    ca4?: number | null,
    ca5?: number | null,
    ca6?: number | null,
    ca7?: number | null,
    ca8?: number | null,
    ca9?: number | null,
    ca10?: number | null,
    contestID: string,
    createdAt: string,
    updatedAt: string,
    contest?:  {
      __typename: "Contest",
      id: string,
      contestID: string,
      sort: number,
      contestContentAnn: string,
      title: string,
      ps1?: string | null,
      ps2?: string | null,
      ps3?: string | null,
      ps4?: string | null,
      ps5?: string | null,
      q1?: string | null,
      q2?: string | null,
      q3?: string | null,
      q4?: string | null,
      q5?: string | null,
      q6?: string | null,
      q7?: string | null,
      q8?: string | null,
      q9?: string | null,
      q10?: string | null,
      a1?: string | null,
      a2?: string | null,
      a3?: string | null,
      a4?: string | null,
      a5?: string | null,
      a6?: string | null,
      a7?: string | null,
      a8?: string | null,
      a9?: string | null,
      a10?: string | null,
      scheduledTime: number,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
      answerAttempts?:  {
        __typename: "ModelContestAnswerConnection",
        nextToken?: string | null,
      } | null,
    } | null,
    owner?: string | null,
  } | null,
};

export type DeleteContestAnswerMutationVariables = {
  input: DeleteContestAnswerInput,
  condition?: ModelContestAnswerConditionInput | null,
};

export type DeleteContestAnswerMutation = {
  deleteContestAnswer?:  {
    __typename: "ContestAnswer",
    id: string,
    contestAnswerID: string,
    score: number,
    ca1?: number | null,
    ca2?: number | null,
    ca3?: number | null,
    ca4?: number | null,
    ca5?: number | null,
    ca6?: number | null,
    ca7?: number | null,
    ca8?: number | null,
    ca9?: number | null,
    ca10?: number | null,
    contestID: string,
    createdAt: string,
    updatedAt: string,
    contest?:  {
      __typename: "Contest",
      id: string,
      contestID: string,
      sort: number,
      contestContentAnn: string,
      title: string,
      ps1?: string | null,
      ps2?: string | null,
      ps3?: string | null,
      ps4?: string | null,
      ps5?: string | null,
      q1?: string | null,
      q2?: string | null,
      q3?: string | null,
      q4?: string | null,
      q5?: string | null,
      q6?: string | null,
      q7?: string | null,
      q8?: string | null,
      q9?: string | null,
      q10?: string | null,
      a1?: string | null,
      a2?: string | null,
      a3?: string | null,
      a4?: string | null,
      a5?: string | null,
      a6?: string | null,
      a7?: string | null,
      a8?: string | null,
      a9?: string | null,
      a10?: string | null,
      scheduledTime: number,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
      answerAttempts?:  {
        __typename: "ModelContestAnswerConnection",
        nextToken?: string | null,
      } | null,
    } | null,
    owner?: string | null,
  } | null,
};

export type GetContestQueryVariables = {
  id: string,
};

export type GetContestQuery = {
  getContest?:  {
    __typename: "Contest",
    id: string,
    contestID: string,
    sort: number,
    contestContentAnn: string,
    title: string,
    ps1?: string | null,
    ps2?: string | null,
    ps3?: string | null,
    ps4?: string | null,
    ps5?: string | null,
    q1?: string | null,
    q2?: string | null,
    q3?: string | null,
    q4?: string | null,
    q5?: string | null,
    q6?: string | null,
    q7?: string | null,
    q8?: string | null,
    q9?: string | null,
    q10?: string | null,
    a1?: string | null,
    a2?: string | null,
    a3?: string | null,
    a4?: string | null,
    a5?: string | null,
    a6?: string | null,
    a7?: string | null,
    a8?: string | null,
    a9?: string | null,
    a10?: string | null,
    scheduledTime: number,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
    answerAttempts?:  {
      __typename: "ModelContestAnswerConnection",
      items?:  Array< {
        __typename: "ContestAnswer",
        id: string,
        contestAnswerID: string,
        score: number,
        ca1?: number | null,
        ca2?: number | null,
        ca3?: number | null,
        ca4?: number | null,
        ca5?: number | null,
        ca6?: number | null,
        ca7?: number | null,
        ca8?: number | null,
        ca9?: number | null,
        ca10?: number | null,
        contestID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null > | null,
      nextToken?: string | null,
    } | null,
  } | null,
};

export type ListContestsQueryVariables = {
  filter?: ModelContestFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListContestsQuery = {
  listContests?:  {
    __typename: "ModelContestConnection",
    items?:  Array< {
      __typename: "Contest",
      id: string,
      contestID: string,
      sort: number,
      contestContentAnn: string,
      title: string,
      ps1?: string | null,
      ps2?: string | null,
      ps3?: string | null,
      ps4?: string | null,
      ps5?: string | null,
      q1?: string | null,
      q2?: string | null,
      q3?: string | null,
      q4?: string | null,
      q5?: string | null,
      q6?: string | null,
      q7?: string | null,
      q8?: string | null,
      q9?: string | null,
      q10?: string | null,
      a1?: string | null,
      a2?: string | null,
      a3?: string | null,
      a4?: string | null,
      a5?: string | null,
      a6?: string | null,
      a7?: string | null,
      a8?: string | null,
      a9?: string | null,
      a10?: string | null,
      scheduledTime: number,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
      answerAttempts?:  {
        __typename: "ModelContestAnswerConnection",
        nextToken?: string | null,
      } | null,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type GetContestAnswerQueryVariables = {
  id: string,
};

export type GetContestAnswerQuery = {
  getContestAnswer?:  {
    __typename: "ContestAnswer",
    id: string,
    contestAnswerID: string,
    score: number,
    ca1?: number | null,
    ca2?: number | null,
    ca3?: number | null,
    ca4?: number | null,
    ca5?: number | null,
    ca6?: number | null,
    ca7?: number | null,
    ca8?: number | null,
    ca9?: number | null,
    ca10?: number | null,
    contestID: string,
    createdAt: string,
    updatedAt: string,
    contest?:  {
      __typename: "Contest",
      id: string,
      contestID: string,
      sort: number,
      contestContentAnn: string,
      title: string,
      ps1?: string | null,
      ps2?: string | null,
      ps3?: string | null,
      ps4?: string | null,
      ps5?: string | null,
      q1?: string | null,
      q2?: string | null,
      q3?: string | null,
      q4?: string | null,
      q5?: string | null,
      q6?: string | null,
      q7?: string | null,
      q8?: string | null,
      q9?: string | null,
      q10?: string | null,
      a1?: string | null,
      a2?: string | null,
      a3?: string | null,
      a4?: string | null,
      a5?: string | null,
      a6?: string | null,
      a7?: string | null,
      a8?: string | null,
      a9?: string | null,
      a10?: string | null,
      scheduledTime: number,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
      answerAttempts?:  {
        __typename: "ModelContestAnswerConnection",
        nextToken?: string | null,
      } | null,
    } | null,
    owner?: string | null,
  } | null,
};

export type ListContestAnswersQueryVariables = {
  filter?: ModelContestAnswerFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListContestAnswersQuery = {
  listContestAnswers?:  {
    __typename: "ModelContestAnswerConnection",
    items?:  Array< {
      __typename: "ContestAnswer",
      id: string,
      contestAnswerID: string,
      score: number,
      ca1?: number | null,
      ca2?: number | null,
      ca3?: number | null,
      ca4?: number | null,
      ca5?: number | null,
      ca6?: number | null,
      ca7?: number | null,
      ca8?: number | null,
      ca9?: number | null,
      ca10?: number | null,
      contestID: string,
      createdAt: string,
      updatedAt: string,
      contest?:  {
        __typename: "Contest",
        id: string,
        contestID: string,
        sort: number,
        contestContentAnn: string,
        title: string,
        ps1?: string | null,
        ps2?: string | null,
        ps3?: string | null,
        ps4?: string | null,
        ps5?: string | null,
        q1?: string | null,
        q2?: string | null,
        q3?: string | null,
        q4?: string | null,
        q5?: string | null,
        q6?: string | null,
        q7?: string | null,
        q8?: string | null,
        q9?: string | null,
        q10?: string | null,
        a1?: string | null,
        a2?: string | null,
        a3?: string | null,
        a4?: string | null,
        a5?: string | null,
        a6?: string | null,
        a7?: string | null,
        a8?: string | null,
        a9?: string | null,
        a10?: string | null,
        scheduledTime: number,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      owner?: string | null,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type OnCreateContestSubscription = {
  onCreateContest?:  {
    __typename: "Contest",
    id: string,
    contestID: string,
    sort: number,
    contestContentAnn: string,
    title: string,
    ps1?: string | null,
    ps2?: string | null,
    ps3?: string | null,
    ps4?: string | null,
    ps5?: string | null,
    q1?: string | null,
    q2?: string | null,
    q3?: string | null,
    q4?: string | null,
    q5?: string | null,
    q6?: string | null,
    q7?: string | null,
    q8?: string | null,
    q9?: string | null,
    q10?: string | null,
    a1?: string | null,
    a2?: string | null,
    a3?: string | null,
    a4?: string | null,
    a5?: string | null,
    a6?: string | null,
    a7?: string | null,
    a8?: string | null,
    a9?: string | null,
    a10?: string | null,
    scheduledTime: number,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
    answerAttempts?:  {
      __typename: "ModelContestAnswerConnection",
      items?:  Array< {
        __typename: "ContestAnswer",
        id: string,
        contestAnswerID: string,
        score: number,
        ca1?: number | null,
        ca2?: number | null,
        ca3?: number | null,
        ca4?: number | null,
        ca5?: number | null,
        ca6?: number | null,
        ca7?: number | null,
        ca8?: number | null,
        ca9?: number | null,
        ca10?: number | null,
        contestID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null > | null,
      nextToken?: string | null,
    } | null,
  } | null,
};

export type OnUpdateContestSubscription = {
  onUpdateContest?:  {
    __typename: "Contest",
    id: string,
    contestID: string,
    sort: number,
    contestContentAnn: string,
    title: string,
    ps1?: string | null,
    ps2?: string | null,
    ps3?: string | null,
    ps4?: string | null,
    ps5?: string | null,
    q1?: string | null,
    q2?: string | null,
    q3?: string | null,
    q4?: string | null,
    q5?: string | null,
    q6?: string | null,
    q7?: string | null,
    q8?: string | null,
    q9?: string | null,
    q10?: string | null,
    a1?: string | null,
    a2?: string | null,
    a3?: string | null,
    a4?: string | null,
    a5?: string | null,
    a6?: string | null,
    a7?: string | null,
    a8?: string | null,
    a9?: string | null,
    a10?: string | null,
    scheduledTime: number,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
    answerAttempts?:  {
      __typename: "ModelContestAnswerConnection",
      items?:  Array< {
        __typename: "ContestAnswer",
        id: string,
        contestAnswerID: string,
        score: number,
        ca1?: number | null,
        ca2?: number | null,
        ca3?: number | null,
        ca4?: number | null,
        ca5?: number | null,
        ca6?: number | null,
        ca7?: number | null,
        ca8?: number | null,
        ca9?: number | null,
        ca10?: number | null,
        contestID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null > | null,
      nextToken?: string | null,
    } | null,
  } | null,
};

export type OnDeleteContestSubscription = {
  onDeleteContest?:  {
    __typename: "Contest",
    id: string,
    contestID: string,
    sort: number,
    contestContentAnn: string,
    title: string,
    ps1?: string | null,
    ps2?: string | null,
    ps3?: string | null,
    ps4?: string | null,
    ps5?: string | null,
    q1?: string | null,
    q2?: string | null,
    q3?: string | null,
    q4?: string | null,
    q5?: string | null,
    q6?: string | null,
    q7?: string | null,
    q8?: string | null,
    q9?: string | null,
    q10?: string | null,
    a1?: string | null,
    a2?: string | null,
    a3?: string | null,
    a4?: string | null,
    a5?: string | null,
    a6?: string | null,
    a7?: string | null,
    a8?: string | null,
    a9?: string | null,
    a10?: string | null,
    scheduledTime: number,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
    answerAttempts?:  {
      __typename: "ModelContestAnswerConnection",
      items?:  Array< {
        __typename: "ContestAnswer",
        id: string,
        contestAnswerID: string,
        score: number,
        ca1?: number | null,
        ca2?: number | null,
        ca3?: number | null,
        ca4?: number | null,
        ca5?: number | null,
        ca6?: number | null,
        ca7?: number | null,
        ca8?: number | null,
        ca9?: number | null,
        ca10?: number | null,
        contestID: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null > | null,
      nextToken?: string | null,
    } | null,
  } | null,
};

export type OnCreateContestAnswerSubscription = {
  onCreateContestAnswer?:  {
    __typename: "ContestAnswer",
    id: string,
    contestAnswerID: string,
    score: number,
    ca1?: number | null,
    ca2?: number | null,
    ca3?: number | null,
    ca4?: number | null,
    ca5?: number | null,
    ca6?: number | null,
    ca7?: number | null,
    ca8?: number | null,
    ca9?: number | null,
    ca10?: number | null,
    contestID: string,
    createdAt: string,
    updatedAt: string,
    contest?:  {
      __typename: "Contest",
      id: string,
      contestID: string,
      sort: number,
      contestContentAnn: string,
      title: string,
      ps1?: string | null,
      ps2?: string | null,
      ps3?: string | null,
      ps4?: string | null,
      ps5?: string | null,
      q1?: string | null,
      q2?: string | null,
      q3?: string | null,
      q4?: string | null,
      q5?: string | null,
      q6?: string | null,
      q7?: string | null,
      q8?: string | null,
      q9?: string | null,
      q10?: string | null,
      a1?: string | null,
      a2?: string | null,
      a3?: string | null,
      a4?: string | null,
      a5?: string | null,
      a6?: string | null,
      a7?: string | null,
      a8?: string | null,
      a9?: string | null,
      a10?: string | null,
      scheduledTime: number,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
      answerAttempts?:  {
        __typename: "ModelContestAnswerConnection",
        nextToken?: string | null,
      } | null,
    } | null,
    owner?: string | null,
  } | null,
};

export type OnUpdateContestAnswerSubscription = {
  onUpdateContestAnswer?:  {
    __typename: "ContestAnswer",
    id: string,
    contestAnswerID: string,
    score: number,
    ca1?: number | null,
    ca2?: number | null,
    ca3?: number | null,
    ca4?: number | null,
    ca5?: number | null,
    ca6?: number | null,
    ca7?: number | null,
    ca8?: number | null,
    ca9?: number | null,
    ca10?: number | null,
    contestID: string,
    createdAt: string,
    updatedAt: string,
    contest?:  {
      __typename: "Contest",
      id: string,
      contestID: string,
      sort: number,
      contestContentAnn: string,
      title: string,
      ps1?: string | null,
      ps2?: string | null,
      ps3?: string | null,
      ps4?: string | null,
      ps5?: string | null,
      q1?: string | null,
      q2?: string | null,
      q3?: string | null,
      q4?: string | null,
      q5?: string | null,
      q6?: string | null,
      q7?: string | null,
      q8?: string | null,
      q9?: string | null,
      q10?: string | null,
      a1?: string | null,
      a2?: string | null,
      a3?: string | null,
      a4?: string | null,
      a5?: string | null,
      a6?: string | null,
      a7?: string | null,
      a8?: string | null,
      a9?: string | null,
      a10?: string | null,
      scheduledTime: number,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
      answerAttempts?:  {
        __typename: "ModelContestAnswerConnection",
        nextToken?: string | null,
      } | null,
    } | null,
    owner?: string | null,
  } | null,
};

export type OnDeleteContestAnswerSubscription = {
  onDeleteContestAnswer?:  {
    __typename: "ContestAnswer",
    id: string,
    contestAnswerID: string,
    score: number,
    ca1?: number | null,
    ca2?: number | null,
    ca3?: number | null,
    ca4?: number | null,
    ca5?: number | null,
    ca6?: number | null,
    ca7?: number | null,
    ca8?: number | null,
    ca9?: number | null,
    ca10?: number | null,
    contestID: string,
    createdAt: string,
    updatedAt: string,
    contest?:  {
      __typename: "Contest",
      id: string,
      contestID: string,
      sort: number,
      contestContentAnn: string,
      title: string,
      ps1?: string | null,
      ps2?: string | null,
      ps3?: string | null,
      ps4?: string | null,
      ps5?: string | null,
      q1?: string | null,
      q2?: string | null,
      q3?: string | null,
      q4?: string | null,
      q5?: string | null,
      q6?: string | null,
      q7?: string | null,
      q8?: string | null,
      q9?: string | null,
      q10?: string | null,
      a1?: string | null,
      a2?: string | null,
      a3?: string | null,
      a4?: string | null,
      a5?: string | null,
      a6?: string | null,
      a7?: string | null,
      a8?: string | null,
      a9?: string | null,
      a10?: string | null,
      scheduledTime: number,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
      answerAttempts?:  {
        __typename: "ModelContestAnswerConnection",
        nextToken?: string | null,
      } | null,
    } | null,
    owner?: string | null,
  } | null,
};
